FIX: Broken pipe issue
egal/php-laravel-event-bus-package pull request #1
Opened 2023-07-05 05:35 UTC by SixSad

2023-07-05 06:32 UTC, rollsover requested changes

2023-07-05 06:32 UTC, rollsover commented on src/RabbitMQEventBus.php
> -}
Пустая строка

2023-07-05 06:32 UTC, rollsover commented on src/RabbitMQEventBus.php
> +            prefetch_size: 0,
Почему?

2023-07-05 06:32 UTC, rollsover commented on src/RabbitMQEventBus.php
> +            a_global: false,
Почему?

2023-07-05 06:32 UTC, rollsover commented on src/RabbitMQEventBus.php
> +        try {
В цикл while с траями не больше N (из конфига, по дефолту 3)

2023-07-05 06:32 UTC, rollsover commented on src/RabbitMQEventBus.php
> +        try {
В цикл while с траями не больше N (из конфига, по дефолту 3)

2023-07-05 06:32 UTC, rollsover commented on src/RabbitMQEventBus.php
> +        $function = function () {
без анонимизации

2023-07-05 06:32 UTC, rollsover commented on src/RabbitMQEventBus.php
> +    {
здесь можно реализовать логику траев, и каждый раз перед выполнением другой логики вызывать эту функцию.

2023-07-05 06:32 UTC, rollsover commented on src/RabbitMQEventBus.php
> +    {
А тут если не законнекчено - коннектить с траями

2023-07-10 08:57 UTC, SixSad commented on src/RabbitMQEventBus.php
> +    {
Переделал на траи

2023-07-10 08:57 UTC, SixSad commented on src/RabbitMQEventBus.php
> +            prefetch_size: 0,
Из параметров метода.
int $prefetch_size int $prefetch_count bool $a_global

2023-07-10 08:57 UTC, SixSad commented on src/RabbitMQEventBus.php
> +            a_global: false,
Из параметров метода.
int $prefetch_size int $prefetch_count bool $a_global

2023-07-10 10:13 UTC, rollsover requested changes

2023-07-10 10:13 UTC, rollsover commented on src/RabbitMQEventBus.php
> +        $this->connectionRetries = $connection['connection_retries'];
тут maxConnectionRetryes

2023-07-10 10:13 UTC, rollsover commented on src/RabbitMQEventBus.php
> +        while ($this->connectionRetries) {
А тут отдельная переменная `currentConnectionTry` и `while currentConnectionTry <= maxConnectionRetryes`

2023-07-10 10:13 UTC, rollsover commented on stubs/config.stub
> +            'connection_retries' => env('EVENT_BUS_CONNECTION_RETRIES', 3),
Тут также названия с префиксом `max`

2023-07-10 10:33 UTC, SixSad commented on stubs/config.stub
> +            'connection_retries' => env('EVENT_BUS_CONNECTION_RETRIES', 3),
+

2023-07-10 10:33 UTC, SixSad commented on src/RabbitMQEventBus.php
> +        while ($this->connectionRetries) {
+

2023-07-10 10:33 UTC, SixSad commented on src/RabbitMQEventBus.php
> +        $this->connectionRetries = $connection['connection_retries'];
+

2023-07-10 11:26 UTC, rollsover commented
```php
    public function connect(): void
    {
        // TODO: if connection is ready – not connect and return;
        
        $failingStreak = 0;

        while (true) {
            try {
                $this->channel = $this->connection->channel();
                $this->channel->queue_declare(
                    queue: $this->queue,
                    passive: false,
                    durable: true,
                    exclusive: false,
                    auto_delete: false,
                    nowait: false,
                    arguments: new AMQPTable(['x-queue-mode' => 'default']),
                );
                $this->channel->queue_bind($this->queue, $this->exchange);
                break;
            } catch (\Exception) {
                $failingStreak++;
                continue;
            }
            
            if ($failingStreak >= $this->maxConnectionRetries) {
                throw new \Exception("Failed connect to RabbitMQ!");
            }
        }
    }
```

2023-07-19 05:47 UTC, rollsover requested changes

2023-07-19 05:47 UTC, rollsover commented on src/RabbitMQEventBus.php
> +                usleep(5000);
В конфиг вынести, и по дефолту `200*$failingStreak`

И поставить после `$failingStreak++;`

2023-07-19 05:47 UTC, rollsover commented on src/RabbitMQEventBus.php
> +                $this->exchange,
в рандомную очередь по uuid сгенерированную

2023-07-19 05:47 UTC, rollsover commented on src/RabbitMQEventBus.php
> +                'testMessage'
также рандомное

2023-07-19 05:47 UTC, rollsover commented on src/RabbitMQEventBus.php
> +                usleep(5000);
`200` из конфига

2023-07-19 05:50 UTC, rollsover requested changes

2023-07-19 05:50 UTC, rollsover commented on src/RabbitMQEventBus.php
> +                throw new \Exception("Failed connect to RabbitMQ!");
Вынести в use

2023-07-19 05:50 UTC, rollsover commented on src/RabbitMQEventBus.php
> +                if (isset($this->channel) && $this->testConnectionMessage()) return;
Вынести за цикл, зачем каждый раз проверять? если ты в этот цикла должен заходить только тогда, когда надо зайти

2023-07-19 08:00 UTC, rollsover requested changes

2023-07-19 08:00 UTC, rollsover commented on src/ConnectionFailedException.php
> +}
Пустая строка

2023-07-19 08:06 UTC, merged